---
- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
- name: Create database for lamp tracker
  become: true
  become_user: postgres
  postgresql_db:
    name: lamp_tracker_db
  vars:
    ansible_ssh_pipelining: true
- name: Create lamp tracker user for database
  become: true
  become_user: postgres
  postgresql_user:
    db: lamp_tracker_db
    name: lamp_tracker
    password: "{{ db_password }}"
    encrypted: true
  vars:
    ansible_ssh_pipelining: true
- name: Enable PostGIS extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: lamp_tracker_db
    state: present
  vars:
    ansible_ssh_pipelining: true
