---
apt_packages:
- apache2
- apache2-utils
- libexpat1
- libapache2-mod-wsgi-py3
- libpq-dev
- python3-alembic
- python3-flask
- python3-pint
- python3-flask-login
- python3-flask-sqlalchemy
- python3-flask-bcrypt
- python3-flask-migrate
- python3-flaskext.wtf
- python3-flask-mail
- python3-psycopg2
- postgresql-16
- postgresql-16-postgis-3
- postgresql-16-postgis-3-scripts
- python3-geopy
- python3-geoalchemy2
- python3-shapely
- python3-overpy
