# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy to Digital Ocean
on:
  push:
    branches: [ "main", "testing" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade --yes
        sudo apt install --yes ansible rsync openssh-client
    - name: Run Ansible playbook
      run: |
        eval `ssh-agent -s`
        echo ${{ secrets.SSH_PRIVATE_KEY }} | tr '*' "\\n" | ssh-add -
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i hosts playbook.yml -e "variable_host='example_server' secret_key=${SECRET_KEY} db_password=${DB_PASSWORD} certbot_admin_email=${CERTBOT_ADMIN_EMAIL}" -vv
